import * as fs from 'fs';
import * as path from 'path';
import {
  Changelog,
  ChangelogEntry,
  ChangelogSection,
  ParsedCommit,
  CommitType
} from './types';

const SECTION_ORDER: Array<{ type: CommitType | 'breaking'; title: string; emoji: string }> = [
  { type: 'breaking', title: '⚠️  BREAKING CHANGES', emoji: '⚠️' },
  { type: 'feat', title: '✨ Features', emoji: '✨' },
  { type: 'fix', title: '🐛 Bug Fixes', emoji: '🐛' },
  { type: 'perf', title: '⚡️ Performance Improvements', emoji: '⚡️' },
  { type: 'refactor', title: '♻️  Code Refactoring', emoji: '♻️' },
  { type: 'docs', title: '📝 Documentation', emoji: '📝' },
  { type: 'test', title: '✅ Tests', emoji: '✅' },
  { type: 'build', title: '📦 Build System', emoji: '📦' },
  { type: 'ci', title: '👷 CI/CD', emoji: '👷' },
  { type: 'style', title: '💄 Styles', emoji: '💄' },
  { type: 'chore', title: '🔧 Chores', emoji: '🔧' },
  { type: 'revert', title: '⏪ Reverts', emoji: '⏪' }
];

export function groupCommitsBySection(commits: ParsedCommit[]): ChangelogSection[] {
  const sections: ChangelogSection[] = [];
  const sectionMap = new Map<CommitType | 'breaking', ParsedCommit[]>();

  for (const commit of commits) {
    if (commit.isBreakingChange) {
      if (!sectionMap.has('breaking')) {
        sectionMap.set('breaking', []);
      }
      sectionMap.get('breaking')!.push(commit);
    }

    if (commit.type !== 'unknown') {
      if (!sectionMap.has(commit.type)) {
        sectionMap.set(commit.type, []);
      }
      sectionMap.get(commit.type)!.push(commit);
    }
  }

  for (const sectionConfig of SECTION_ORDER) {
    const sectionCommits = sectionMap.get(sectionConfig.type);
    if (sectionCommits && sectionCommits.length > 0) {
      sections.push({
        title: sectionConfig.title,
        type: sectionConfig.type,
        commits: sectionCommits
      });
    }
  }

  return sections;
}

export function formatCommitForChangelog(commit: ParsedCommit): string {
  const scopePart = commit.scope ? `**${commit.scope}**: ` : '';
  const sha = commit.sha.substring(0, 7);
  let line = `- ${scopePart}${commit.subject} (${sha})`;

  if (commit.isBreakingChange && commit.breakingChangeDescription) {
    line += `\n    > ⚠️  ${commit.breakingChangeDescription}`;
  }

  return line;
}

export function formatSectionForMarkdown(section: ChangelogSection): string {
  if (section.commits.length === 0) return '';

  const lines: string[] = [];
  lines.push(`### ${section.title}`);
  lines.push('');

  for (const commit of section.commits) {
    lines.push(formatCommitForChangelog(commit));
  }

  lines.push('');
  return lines.join('\n');
}

export function formatEntryForMarkdown(entry: ChangelogEntry): string {
  const lines: string[] = [];
  const dateStr = entry.date || new Date().toISOString().split('T')[0];

  lines.push(`## [${entry.version}] - ${dateStr}`);
  lines.push('');

  if (entry.sections.length === 0) {
    lines.push('*No significant changes.*');
    lines.push('');
  } else {
    for (const section of entry.sections) {
      lines.push(formatSectionForMarkdown(section));
    }
  }

  return lines.join('\n');
}

export function formatFullChangelog(entries: ChangelogEntry[]): string {
  const lines: string[] = [];

  lines.push('# Changelog');
  lines.push('');
  lines.push('> All notable changes to this project will be documented in this file.');
  lines.push('> Generated by [smart-release].');
  lines.push('');

  for (const entry of entries) {
    lines.push('---');
    lines.push('');
    lines.push(formatEntryForMarkdown(entry));
  }

  return lines.join('\n');
}

export function generateChangelogEntry(
  version: string,
  commits: ParsedCommit[],
  date: string = new Date().toISOString().split('T')[0],
  url?: string
): ChangelogEntry {
  const sections = groupCommitsBySection(commits);

  return {
    version,
    date,
    sections,
    url
  };
}

export function writeChangelogFile(
  changelog: Changelog,
  filePath: string = 'CHANGELOG.md'
): void {
  fs.writeFileSync(filePath, changelog.raw, 'utf-8');
}

export function readChangelogFile(filePath: string = 'CHANGELOG.md'): string | null {
  try {
    if (fs.existsSync(filePath)) {
      return fs.readFileSync(filePath, 'utf-8');
    }
    return null;
  } catch {
    return null;
  }
}

export function prependChangelogEntry(
  existingContent: string | null,
  newEntry: ChangelogEntry
): Changelog {
  const newEntryMarkdown = formatEntryForMarkdown(newEntry);

  let raw: string;
  const entries: ChangelogEntry[] = [newEntry];

  if (existingContent) {
    const headerEndIdx = existingContent.indexOf('## [');
    if (headerEndIdx !== -1) {
      const header = existingContent.substring(0, headerEndIdx).trim();
      const rest = existingContent.substring(headerEndIdx);
      raw = `${header}\n\n---\n\n${newEntryMarkdown}\n---\n\n${rest}`;
    } else {
      raw = `${existingContent.trim()}\n\n---\n\n${newEntryMarkdown}`;
    }
  } else {
    const lines: string[] = [];
    lines.push('# Changelog');
    lines.push('');
    lines.push('> All notable changes to this project will be documented in this file.');
    lines.push('> Generated by [smart-release].');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push(newEntryMarkdown);
    raw = lines.join('\n');
  }

  return { entries, raw };
}

export function generateChangelogForRelease(
  version: string,
  commits: ParsedCommit[],
  date?: string
): string {
  const entry = generateChangelogEntry(version, commits, date);
  return formatEntryForMarkdown(entry);
}
